//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.14 at 01:49:47 PM CEST 
//


package XmlData.Configurations;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Tipo che definisce un elenco di dati
 * 
 * <p>Java class for data complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="data">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="contenitori_xml" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contatti_xml" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="links_xml" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="biblio_xml" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="collezione_xml" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "data", propOrder = {

})
public class Data {

    @XmlElement(name = "contenitori_xml", required = true)
    protected String contenitoriXml;
    @XmlElement(name = "contatti_xml", required = true)
    protected String contattiXml;
    @XmlElement(name = "links_xml", required = true)
    protected String linksXml;
    @XmlElement(name = "biblio_xml", required = true)
    protected String biblioXml;
    @XmlElement(name = "collezione_xml", required = true)
    protected String collezioneXml;

    /**
     * Gets the value of the contenitoriXml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContenitoriXml() {
        return contenitoriXml;
    }

    /**
     * Sets the value of the contenitoriXml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContenitoriXml(String value) {
        this.contenitoriXml = value;
    }

    /**
     * Gets the value of the contattiXml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContattiXml() {
        return contattiXml;
    }

    /**
     * Sets the value of the contattiXml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContattiXml(String value) {
        this.contattiXml = value;
    }

    /**
     * Gets the value of the linksXml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinksXml() {
        return linksXml;
    }

    /**
     * Sets the value of the linksXml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinksXml(String value) {
        this.linksXml = value;
    }

    /**
     * Gets the value of the biblioXml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBiblioXml() {
        return biblioXml;
    }

    /**
     * Sets the value of the biblioXml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBiblioXml(String value) {
        this.biblioXml = value;
    }

    /**
     * Gets the value of the collezioneXml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollezioneXml() {
        return collezioneXml;
    }

    /**
     * Sets the value of the collezioneXml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollezioneXml(String value) {
        this.collezioneXml = value;
    }

}
