//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.12 at 10:20:47 AM CEST 
//


package XmlData.Configurations;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Tipo che definisce un elenco di dirs
 * 
 * <p>Java class for dirs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dirs">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="base_dir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="monete_dir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="backup_dir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="biblioteca_dir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="html_dir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="latex_dir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="qr_dir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dirs", propOrder = {

})
public class Dirs {

    @XmlElement(name = "base_dir", required = true)
    protected String baseDir;
    @XmlElement(name = "monete_dir", required = true)
    protected String moneteDir;
    @XmlElement(name = "backup_dir", required = true)
    protected String backupDir;
    @XmlElement(name = "biblioteca_dir", required = true)
    protected String bibliotecaDir;
    @XmlElement(name = "html_dir", required = true)
    protected String htmlDir;
    @XmlElement(name = "latex_dir", required = true)
    protected String latexDir;
    @XmlElement(name = "qr_dir", required = true)
    protected String qrDir;

    /**
     * Gets the value of the baseDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseDir() {
        return baseDir;
    }

    /**
     * Sets the value of the baseDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseDir(String value) {
        this.baseDir = value;
    }

    /**
     * Gets the value of the moneteDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoneteDir() {
        return moneteDir;
    }

    /**
     * Sets the value of the moneteDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoneteDir(String value) {
        this.moneteDir = value;
    }

    /**
     * Gets the value of the backupDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackupDir() {
        return backupDir;
    }

    /**
     * Sets the value of the backupDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackupDir(String value) {
        this.backupDir = value;
    }

    /**
     * Gets the value of the bibliotecaDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBibliotecaDir() {
        return bibliotecaDir;
    }

    /**
     * Sets the value of the bibliotecaDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBibliotecaDir(String value) {
        this.bibliotecaDir = value;
    }

    /**
     * Gets the value of the htmlDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHtmlDir() {
        return htmlDir;
    }

    /**
     * Sets the value of the htmlDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHtmlDir(String value) {
        this.htmlDir = value;
    }

    /**
     * Gets the value of the latexDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLatexDir() {
        return latexDir;
    }

    /**
     * Sets the value of the latexDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLatexDir(String value) {
        this.latexDir = value;
    }

    /**
     * Gets the value of the qrDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQrDir() {
        return qrDir;
    }

    /**
     * Sets the value of the qrDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQrDir(String value) {
        this.qrDir = value;
    }

}
