//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.23 at 01:08:23 PM CEST 
//


package XmlData.Configurations;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Tipo che definisce un elenco di template
 * 
 * <p>Java class for templates complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="templates">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="xml_moneta_void_instance" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "templates", propOrder = {

})
public class Templates {

    @XmlElement(name = "xml_moneta_void_instance", required = true)
    protected String xmlMonetaVoidInstance;

    /**
     * Gets the value of the xmlMonetaVoidInstance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlMonetaVoidInstance() {
        return xmlMonetaVoidInstance;
    }

    /**
     * Sets the value of the xmlMonetaVoidInstance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlMonetaVoidInstance(String value) {
        this.xmlMonetaVoidInstance = value;
    }

}
