//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.22 at 09:10:22 AM CEST 
//


package XmlData.Configurations;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Tipo che definisce un elenco di trasformazioni xsl
 * 
 * <p>Java class for transformations complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="transformations">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="xsl_latex" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="xsl_html" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="xsl_txt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "transformations", propOrder = {

})
public class Transformations {

    @XmlElement(name = "xsl_latex", required = true)
    protected String xslLatex;
    @XmlElement(name = "xsl_html", required = true)
    protected String xslHtml;
    @XmlElement(name = "xsl_txt", required = true)
    protected String xslTxt;

    /**
     * Gets the value of the xslLatex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXslLatex() {
        return xslLatex;
    }

    /**
     * Sets the value of the xslLatex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXslLatex(String value) {
        this.xslLatex = value;
    }

    /**
     * Gets the value of the xslHtml property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXslHtml() {
        return xslHtml;
    }

    /**
     * Sets the value of the xslHtml property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXslHtml(String value) {
        this.xslHtml = value;
    }

    /**
     * Gets the value of the xslTxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXslTxt() {
        return xslTxt;
    }

    /**
     * Sets the value of the xslTxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXslTxt(String value) {
        this.xslTxt = value;
    }

}
