//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.12 at 02:22:56 PM CEST 
//


package XmlData.Biblioteca;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the XmlData.Biblioteca package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: XmlData.Biblioteca
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Biblioteca }
     * 
     */
    public Biblioteca createBiblioteca() {
        return new Biblioteca();
    }

    /**
     * Create an instance of {@link Argomenti }
     * 
     */
    public Argomenti createArgomenti() {
        return new Argomenti();
    }

    /**
     * Create an instance of {@link Supporti }
     * 
     */
    public Supporti createSupporti() {
        return new Supporti();
    }

    /**
     * Create an instance of {@link Cataloghi }
     * 
     */
    public Cataloghi createCataloghi() {
        return new Cataloghi();
    }

    /**
     * Create an instance of {@link Catalogo }
     * 
     */
    public Catalogo createCatalogo() {
        return new Catalogo();
    }

    /**
     * Create an instance of {@link Libri }
     * 
     */
    public Libri createLibri() {
        return new Libri();
    }

    /**
     * Create an instance of {@link Autori }
     * 
     */
    public Autori createAutori() {
        return new Autori();
    }

    /**
     * Create an instance of {@link Librotype }
     * 
     */
    public Librotype createLibrotype() {
        return new Librotype();
    }

}
