//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.15 at 08:56:39 AM CEST 
//


package XmlData.Biblioteca;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="libri" type="{http://gestColl/biblioteca}libri"/>
 *         &lt;element name="cataloghi" type="{http://gestColl/biblioteca}cataloghi" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "biblioteca")
public class Biblioteca {

    @XmlElement(required = true)
    protected Libri libri;
    protected Cataloghi cataloghi;

    /**
     * Gets the value of the libri property.
     * 
     * @return
     *     possible object is
     *     {@link Libri }
     *     
     */
    public Libri getLibri() {
        return libri;
    }

    /**
     * Sets the value of the libri property.
     * 
     * @param value
     *     allowed object is
     *     {@link Libri }
     *     
     */
    public void setLibri(Libri value) {
        this.libri = value;
    }

    /**
     * Gets the value of the cataloghi property.
     * 
     * @return
     *     possible object is
     *     {@link Cataloghi }
     *     
     */
    public Cataloghi getCataloghi() {
        return cataloghi;
    }

    /**
     * Sets the value of the cataloghi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cataloghi }
     *     
     */
    public void setCataloghi(Cataloghi value) {
        this.cataloghi = value;
    }

}
