//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.23 at 12:03:17 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.contenitori.org", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package XmlData.Contenitori;

