//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.14 at 01:49:47 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://gestColl/configurations", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package XmlData.Configurations;
