//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.11 at 10:46:23 AM CEST 
//


package XmlData.Moneta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for datiArtistici complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="datiArtistici">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dritto" type="{http://gestColl/coins}descrizioni"/>
 *         &lt;element name="rovescio" type="{http://gestColl/coins}descrizioni"/>
 *         &lt;element name="taglio" type="{http://gestColl/coins}descrizioni" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "datiArtistici", propOrder = {
    "dritto",
    "rovescio",
    "taglio"
})
public class DatiArtistici {

    @XmlElement(required = true)
    protected Descrizioni dritto;
    @XmlElement(required = true)
    protected Descrizioni rovescio;
    protected Descrizioni taglio;

    /**
     * Gets the value of the dritto property.
     * 
     * @return
     *     possible object is
     *     {@link Descrizioni }
     *     
     */
    public Descrizioni getDritto() {
        return dritto;
    }

    /**
     * Sets the value of the dritto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Descrizioni }
     *     
     */
    public void setDritto(Descrizioni value) {
        this.dritto = value;
    }

    /**
     * Gets the value of the rovescio property.
     * 
     * @return
     *     possible object is
     *     {@link Descrizioni }
     *     
     */
    public Descrizioni getRovescio() {
        return rovescio;
    }

    /**
     * Sets the value of the rovescio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Descrizioni }
     *     
     */
    public void setRovescio(Descrizioni value) {
        this.rovescio = value;
    }

    /**
     * Gets the value of the taglio property.
     * 
     * @return
     *     possible object is
     *     {@link Descrizioni }
     *     
     */
    public Descrizioni getTaglio() {
        return taglio;
    }

    /**
     * Sets the value of the taglio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Descrizioni }
     *     
     */
    public void setTaglio(Descrizioni value) {
        this.taglio = value;
    }

}
