//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 10:19:40 PM CEST 
//

package XmlData.Moneta;

import gestXml.Tooltipper;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Tipo che definisce una legenda
 * 
 * <p>
 * Java class for legenda complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="legenda">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="testo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="scioglimento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "legenda", propOrder = {

})
public class Legenda implements Tooltipper {

	protected String scioglimento;
	@XmlElement(required = true)
	protected String testo;

	/**
	 * Gets the value of the scioglimento property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getScioglimento() {
		return scioglimento;
	}

	/**
	 * Gets the value of the testo property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTesto() {
		return testo;
	}

	/**
	 * Sets the value of the scioglimento property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setScioglimento(String value) {
		this.scioglimento = value;
	}

	/**
	 * Sets the value of the testo property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTesto(String value) {
		this.testo = value;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return this.getTesto();
	}

	@Override
	public String toTooltip() {
		return this.getScioglimento();
	}

}
