//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.14 at 12:30:04 PM CEST 
//


package XmlData.Moneta;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Descrizione di una moneta
 * 
 * <p>Java class for moneta complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="moneta">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="paese" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="autorita" type="{http://gestColl/coins}autorita" minOccurs="0"/>
 *         &lt;element name="anno" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nominale" type="{http://gestColl/coins}nominale"/>
 *         &lt;element name="zecca" type="{http://gestColl/coins}zecca" minOccurs="0"/>
 *         &lt;element name="zecchieri" type="{http://gestColl/coins}zecchieri" minOccurs="0"/>
 *         &lt;element name="datiArtistici" type="{http://gestColl/coins}datiArtistici"/>
 *         &lt;element name="datiFisici" type="{http://gestColl/coins}datiFisici"/>
 *         &lt;element name="datiAcquisto" type="{http://gestColl/coins}datiAcquisto"/>
 *         &lt;element name="posizione" type="{http://gestColl/coins}posizione" minOccurs="0"/>
 *         &lt;element name="grado" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="note" type="{http://gestColl/coins}note" minOccurs="0"/>
 *         &lt;element name="letteratura" type="{http://gestColl/coins}letteratura" minOccurs="0"/>
 *         &lt;element name="itemAddizionali" type="{http://gestColl/coins}documentiAggiuntivi" minOccurs="0"/>
 *         &lt;element name="revisione" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/all>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "moneta", propOrder = {

})
public class Moneta {

    @XmlElement(required = true)
    protected String paese;
    protected Autorita autorita;
    protected String anno;
    @XmlElement(required = true)
    protected Nominale nominale;
    protected Zecca zecca;
    protected Zecchieri zecchieri;
    @XmlElement(required = true)
    protected DatiArtistici datiArtistici;
    @XmlElement(required = true)
    protected DatiFisici datiFisici;
    @XmlElement(required = true)
    protected DatiAcquisto datiAcquisto;
    protected Posizione posizione;
    protected String grado;
    protected Note note;
    protected Letteratura letteratura;
    protected DocumentiAggiuntivi itemAddizionali;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar revisione;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the paese property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaese() {
        return paese;
    }

    /**
     * Sets the value of the paese property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaese(String value) {
        this.paese = value;
    }

    /**
     * Gets the value of the autorita property.
     * 
     * @return
     *     possible object is
     *     {@link Autorita }
     *     
     */
    public Autorita getAutorita() {
        return autorita;
    }

    /**
     * Sets the value of the autorita property.
     * 
     * @param value
     *     allowed object is
     *     {@link Autorita }
     *     
     */
    public void setAutorita(Autorita value) {
        this.autorita = value;
    }

    /**
     * Gets the value of the anno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnno() {
        return anno;
    }

    /**
     * Sets the value of the anno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnno(String value) {
        this.anno = value;
    }

    /**
     * Gets the value of the nominale property.
     * 
     * @return
     *     possible object is
     *     {@link Nominale }
     *     
     */
    public Nominale getNominale() {
        return nominale;
    }

    /**
     * Sets the value of the nominale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nominale }
     *     
     */
    public void setNominale(Nominale value) {
        this.nominale = value;
    }

    /**
     * Gets the value of the zecca property.
     * 
     * @return
     *     possible object is
     *     {@link Zecca }
     *     
     */
    public Zecca getZecca() {
        return zecca;
    }

    /**
     * Sets the value of the zecca property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zecca }
     *     
     */
    public void setZecca(Zecca value) {
        this.zecca = value;
    }

    /**
     * Gets the value of the zecchieri property.
     * 
     * @return
     *     possible object is
     *     {@link Zecchieri }
     *     
     */
    public Zecchieri getZecchieri() {
        return zecchieri;
    }

    /**
     * Sets the value of the zecchieri property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zecchieri }
     *     
     */
    public void setZecchieri(Zecchieri value) {
        this.zecchieri = value;
    }

    /**
     * Gets the value of the datiArtistici property.
     * 
     * @return
     *     possible object is
     *     {@link DatiArtistici }
     *     
     */
    public DatiArtistici getDatiArtistici() {
        return datiArtistici;
    }

    /**
     * Sets the value of the datiArtistici property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiArtistici }
     *     
     */
    public void setDatiArtistici(DatiArtistici value) {
        this.datiArtistici = value;
    }

    /**
     * Gets the value of the datiFisici property.
     * 
     * @return
     *     possible object is
     *     {@link DatiFisici }
     *     
     */
    public DatiFisici getDatiFisici() {
        return datiFisici;
    }

    /**
     * Sets the value of the datiFisici property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiFisici }
     *     
     */
    public void setDatiFisici(DatiFisici value) {
        this.datiFisici = value;
    }

    /**
     * Gets the value of the datiAcquisto property.
     * 
     * @return
     *     possible object is
     *     {@link DatiAcquisto }
     *     
     */
    public DatiAcquisto getDatiAcquisto() {
        return datiAcquisto;
    }

    /**
     * Sets the value of the datiAcquisto property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiAcquisto }
     *     
     */
    public void setDatiAcquisto(DatiAcquisto value) {
        this.datiAcquisto = value;
    }

    /**
     * Gets the value of the posizione property.
     * 
     * @return
     *     possible object is
     *     {@link Posizione }
     *     
     */
    public Posizione getPosizione() {
        return posizione;
    }

    /**
     * Sets the value of the posizione property.
     * 
     * @param value
     *     allowed object is
     *     {@link Posizione }
     *     
     */
    public void setPosizione(Posizione value) {
        this.posizione = value;
    }

    /**
     * Gets the value of the grado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrado() {
        return grado;
    }

    /**
     * Sets the value of the grado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrado(String value) {
        this.grado = value;
    }

    /**
     * Gets the value of the note property.
     * 
     * @return
     *     possible object is
     *     {@link Note }
     *     
     */
    public Note getNote() {
        return note;
    }

    /**
     * Sets the value of the note property.
     * 
     * @param value
     *     allowed object is
     *     {@link Note }
     *     
     */
    public void setNote(Note value) {
        this.note = value;
    }

    /**
     * Gets the value of the letteratura property.
     * 
     * @return
     *     possible object is
     *     {@link Letteratura }
     *     
     */
    public Letteratura getLetteratura() {
        return letteratura;
    }

    /**
     * Sets the value of the letteratura property.
     * 
     * @param value
     *     allowed object is
     *     {@link Letteratura }
     *     
     */
    public void setLetteratura(Letteratura value) {
        this.letteratura = value;
    }

    /**
     * Gets the value of the itemAddizionali property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentiAggiuntivi }
     *     
     */
    public DocumentiAggiuntivi getItemAddizionali() {
        return itemAddizionali;
    }

    /**
     * Sets the value of the itemAddizionali property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentiAggiuntivi }
     *     
     */
    public void setItemAddizionali(DocumentiAggiuntivi value) {
        this.itemAddizionali = value;
    }

    /**
     * Gets the value of the revisione property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRevisione() {
        return revisione;
    }

    /**
     * Sets the value of the revisione property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRevisione(XMLGregorianCalendar value) {
        this.revisione = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
