//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.11 at 10:46:23 AM CEST 
//


package XmlData.Moneta;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the XmlData.Moneta package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: XmlData.Moneta
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Nominale }
     * 
     */
    public Nominale createNominale() {
        return new Nominale();
    }

    /**
     * Create an instance of {@link Posizione }
     * 
     */
    public Posizione createPosizione() {
        return new Posizione();
    }

    /**
     * Create an instance of {@link DatiAcquisto }
     * 
     */
    public DatiAcquisto createDatiAcquisto() {
        return new DatiAcquisto();
    }

    /**
     * Create an instance of {@link Misura }
     * 
     */
    public Misura createMisura() {
        return new Misura();
    }

    /**
     * Create an instance of {@link Autorita }
     * 
     */
    public Autorita createAutorita() {
        return new Autorita();
    }

    /**
     * Create an instance of {@link DatiFisici }
     * 
     */
    public DatiFisici createDatiFisici() {
        return new DatiFisici();
    }

    /**
     * Create an instance of {@link Zecca }
     * 
     */
    public Zecca createZecca() {
        return new Zecca();
    }

    /**
     * Create an instance of {@link Zecchiere }
     * 
     */
    public Zecchiere createZecchiere() {
        return new Zecchiere();
    }

    /**
     * Create an instance of {@link Letteratura }
     * 
     */
    public Letteratura createLetteratura() {
        return new Letteratura();
    }

    /**
     * Create an instance of {@link Moneta }
     * 
     */
    public Moneta createMoneta() {
        return new Moneta();
    }

    /**
     * Create an instance of {@link DatiArtistici }
     * 
     */
    public DatiArtistici createDatiArtistici() {
        return new DatiArtistici();
    }

    /**
     * Create an instance of {@link Zecchieri }
     * 
     */
    public Zecchieri createZecchieri() {
        return new Zecchieri();
    }

    /**
     * Create an instance of {@link DocumentiAggiuntivi }
     * 
     */
    public DocumentiAggiuntivi createDocumentiAggiuntivi() {
        return new DocumentiAggiuntivi();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link DocumentoAddizionale }
     * 
     */
    public DocumentoAddizionale createDocumentoAddizionale() {
        return new DocumentoAddizionale();
    }

    /**
     * Create an instance of {@link Descrizioni }
     * 
     */
    public Descrizioni createDescrizioni() {
        return new Descrizioni();
    }

    /**
     * Create an instance of {@link Legenda }
     * 
     */
    public Legenda createLegenda() {
        return new Legenda();
    }

    /**
     * Create an instance of {@link Libro }
     * 
     */
    public Libro createLibro() {
        return new Libro();
    }

    /**
     * Create an instance of {@link Asta }
     * 
     */
    public Asta createAsta() {
        return new Asta();
    }

}
